post http://20.244.56.144/evaluation-service/register
Content-Type: application/json

{
    "email" : "thrinathpothineni@gmail.com",
    "name"  : "Pothineni Thrinath",
    "mobileNo" : "9347001342",
    "githubUsername" : "THRINATH3",
    "rollNo" : "22501A05E9",
    "accessCode" : "eHWNzt" 
}
###

post http://20.244.56.144/evaluation-service/auth
Content-Type: application/json

{
    "email" : "thrinathpothineni@gmail.com",
    "name"  : "Pothineni Thrinath",
    "rollNo" : "22501A05E9",
    "accessCode" : "eHWNzt" ,
    "clientID": "4b319d88-13b2-4b00-819f-22451d5a991d",
    "clientSecret": "kuXjZSUtHezCbPYJ"
}

### Logging middle-ware framework
post http://20.244.56.144/evaluation-service/logs
Content-Type: application/json
Authorization: 4b319d88-13b2-4b00-819f-22451d5a991d:kuXjZSUtHezCbPYJ

{
    "stack": "backend",
    "level": "error",
    "package":"hanler",
    "message":"received string, expected a bool"
}
